FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.23-openshift-4.19 AS builder
WORKDIR /go/src/github.com/k8snetworkplumbingwg/linuxptp-daemon
RUN git clone -b main https://github.com/edcdavid/linuxptp-daemon-upstream.git  /go/src/github.com/k8snetworkplumbingwg/linuxptp-daemon

RUN make clean && make

FROM quay.io/deliedit/test:lptpd-base


COPY --from=builder /go/src/github.com/k8snetworkplumbingwg/linuxptp-daemon/bin/ptp /usr/local/bin/

CMD ["/usr/local/bin/ptp"]